# Generated by Django 5.1 on 2024-08-23 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField(default=0)),
                ('product_img', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('product_description', models.TextField(blank=True, default='')),
            ],
        ),
    ]
